---
title: "Join samples with survey data"
author: "Cob Staines"
output: html_document
---

# Config
```{r}
librarian::shelf(tidyverse, here, yaml, dbplyr, RPostgres, DBI, ribbitrrr, janitor, rio)

# import run config file
run_dir = here("16S_sequence_processing", "runs", "penn_2026-03-10")

# read in config file
config = read_yaml(here(run_dir, "output", "metadata", "config.yml"))

# sample map out file
map_out = here(run_dir, "output", paste0(config$run$name, "_07_sample_id_map.csv"))

# establish database connection
dbcon = hopToDB("ribbitr")

# db table pointers
db_edna = tbl(dbcon, Id("survey_data", "edna_collection"))
db_env = tbl(dbcon, Id("survey_data", "environmental"))
db_survey = tbl(dbcon, Id("survey_data", "survey"))
db_visit = tbl(dbcon, Id("survey_data", "visit"))
db_site = tbl(dbcon, Id("survey_data", "site"))
db_region = tbl(dbcon, Id("survey_data", "region"))
db_country = tbl(dbcon, Id("survey_data", "country"))

```

```{r}
# # load classified ASVs
# asv_classified = read_csv(here(run_dir, "output", paste0(config$run$name, "_hybrid_classification.csv")))

# read in methods lookup file
methods_lookup = import(here(Sys.getenv("data_dir"), "edna_results", "Illumina_runs_for_paper_2026-03-05.xlsx")) %>%
  clean_names() %>%
  mutate(sequencing_sample_name = if_else(grepl("PENN_", sequencing_sample_name),
                                          gsub("PENN-", "PENN_", gsub("_", "-", sequencing_sample_name)),
                                          sequencing_sample_name),
         edna_sample_name = if_else(grepl("PAN_22", id_e_dna_sample),
                                    id_e_dna_sample_edited,
                                    id_e_dna_sample),
         edna_sample_name = gsub("(^[0-9]{6})_", "\\1_eDNA_", edna_sample_name),
         edna_sample_name = if_else(grepl("^Pe_eDNA\\d{5}$", edna_sample_name), gsub("Pe_eDNA00", "Pe_23_eDNA_", edna_sample_name), edna_sample_name)) %>%
  filter(!is.na(edna_sample_name),
         edna_sample_name != "NA") %>%
  rename(illumina_sample_raw = sequencing_sample_name,
         edna_sample_name_lookup = edna_sample_name) %>%
  select(edna_sample_name_lookup,
         illumina_sample_raw)

# samples
feature_table =
  read_tsv(here(run_dir, "/analysis/s06_denoised_16S_eDNA/sample_table/feature-table.tsv"), skip = 1) %>%
  as.data.frame() %>%
  rename("asv_id" = "#OTU ID") %>%
  arrange(asv_id)

feature_long = feature_table %>%
  pivot_longer(cols = -asv_id,
               names_to = "illumina_sample_raw",
               values_to = "asv_count") %>%
  filter(asv_count != 0) %>%
  left_join(methods_lookup, by = "illumina_sample_raw") %>%
  mutate(edna_sample_name = gsub("-B$", "", illumina_sample_raw),
         edna_sample_name = gsub("(_\\d{2}-)(\\d{2}$)", "\\10\\2", edna_sample_name),
         edna_sample_name = gsub("^Pe_(\\d{2})-", "Pe_\\1_eDNA_", edna_sample_name),
         edna_sample_name = gsub("(^Pe_\\d{2}_eDNA_\\d{3})-d.*", "\\1", edna_sample_name),
         edna_sample_name = coalesce(edna_sample_name_lookup, edna_sample_name)) %>%
  select(edna_sample_name,
         illumina_sample_raw,
         asv_id,
         asv_count)

unique_samples = feature_long %>%
  select(edna_sample_name,
         illumina_sample_raw) %>%
  distinct() %>%
  arrange(edna_sample_name)

# survey data
edna_collection = db_edna %>%
  left_join(db_survey, by = "survey_id") %>%
  left_join(db_visit, by = "visit_id") %>%
  left_join(db_site, by = "site_id") %>%
  left_join(db_region, by = "region_id") %>%
  left_join(db_country, by = "country_id") %>%
  select(all_of(colnames(db_edna)),
         transect,
         site,
         date,
         visit_id,
         region,
         country) %>%
  collect()

samps_joined = unique_samples %>%
  left_join(edna_collection, by = "edna_sample_name") %>%
  mutate(lab_control = case_when(
    grepl("NC|Negative", illumina_sample_raw) ~ "negative",
    grepl("Positive", illumina_sample_raw) ~ "positive",
    .default = NA
  ))

sample_map_out = samps_joined %>%
  select(illumina_sample_raw,
         edna_id,
         edna_sample_name,
         negative_control,
         negative_control_group_id) %>%
  distinct() %>%
  filter(!is.na(edna_id))

write.csv(sample_map_out, map_out, row.names = FALSE)
# 
# env_visit = db_env %>%
#   left_join(db_survey, by = "survey_id") %>%
#   left_join(db_visit, by = "visit_id") %>%
#   filter(visit_id %in% samps_joined$visit_id) %>%
#   collect() %>%
#   arrange(water_time) %>%
#   group_by(visit_id, transect) %>%
#   slice_head(n = 1) %>%
#   ungroup()
# 
# samps_env_joined = samps_joined %>%
#   left_join(env_visit %>%
#               select(visit_id,
#                      transect,
#                      any_of(colnames(db_env))), by = c("visit_id", "transect")) %>%
#   select(illumina_sample_name,
#          site,
#          transect,
#          date,
#          collection_time,
#          collection_location,
#          filter_date,
#          filter_method,
#          filter_size_um,
#          filter_volume_ml,
#          filter_start_time,
#          filter_end_time,
#          negative_control,
#          negative_control_group_id,
#          comments_edna,
#          comments_lab,
#          edna_transect_m,
#          edna_latitude,
#          edna_longitude,
#          air_time,
#          air_temp_c,
#          wind_speed_m_s,
#          cloud_cover_percent,
#          water_time,
#          water_temp_c,
#          p_h,
#          tds_ppm,
#          salinity_ppt,
#          conductivity_us_cm,
#          visit_id) %>%
#   arrange(site, transect, date, collection_location, filter_method, filter_size_um)
# 
# write.csv(feature_long, paste0(config$run$runDir, "/output/", config$run$name, "_feature_table_long.csv"), row.names = FALSE)
# 
# write.csv(samps_env_joined, paste0(config$run$runDir, "/output/", config$run$name, "_samples_environment.csv"), row.names = FALSE)
# 
# # complete output
# sample_output = feature_long %>%
#   left_join(asv_classified, by = "asv_id") %>%
#   left_join(samps_env_joined, by = "illumina_sample_name") %>%
#   arrange(site, transect, date, collection_location, filter_method, filter_size_um, desc(asv_count))
# 
# write.csv(sample_output, paste0(config$run$runDir, "/output/", config$run$name, "_samples_environment_asv_taxonomy.csv"), row.names = FALSE)
# 
# # drop taxa in negative controls
# 
# ## within negative control group, list all identified taxa in negative control
# nc_filter_group = sample_output %>%
#   filter(negative_control) %>%
#   filter(!is.na(method))
# 
# nc_filter_global = sample_output %>%
#   filter(grepl("^[A-Z]{2}\\d{3}$", illumina_sample_name)) %>%
#   filter(!is.na(method))
# 
# # antijoin with each group at highest taxon level
# sample_nc_filter = sample_output %>%
#   anti_join(nc_filter_group, by = c("asv_id", "negative_control_group_id")) %>%
#   anti_join(nc_filter_global, by = c("asv_id")) %>%
#   filter(!is.na(method))
# 
# sample_filter_all = sample_nc_filter %>%
#   bind_rows(samps_env_joined %>%
#               filter(!is.na(site),
#                      !negative_control)) %>%
#   mutate(asv_count = if_else(is.na(asv_count), 0, asv_count))
#   
# write.csv(sample_filter_all, paste0(config$run$runDir, "/output/", config$run$name, "_all_samples_nc_filter.csv"), row.names = FALSE)
```