---
title: "09_export_prelim_results"
output: html_document
---

# config
```{r}
librarian::shelf(tidyverse, yaml, here, phylotools, dbplyr, RPostgres, DBI, ribbitrrr)

# import run config file
run_dir = here("16S_sequence_processing", "runs", "penn_2026-03-10")

# read in config file
config = read_yaml(here(run_dir, "output", "metadata", "config.yml"))

# control output file
results_out = here(run_dir, "output", paste0(config$run$name, "_09_prelim_results.csv"))

metadata_out = here(run_dir, "output", paste0(config$run$name, "_09_prelim_results_metadata.csv"))

# establish database connection
dbcon = hopToDB("ribbitr")

```

# load data
```{r}
# controlled features
asv_controlled = read_csv(here(run_dir, "output", paste0(config$run$name, "_08_asv_controlled.csv")))

# sequences
asv_seq =
  read.fasta(here(run_dir, "analysis", "s06_denoised_16S_eDNA", "representative_sequences", 
                           list.files(here(run_dir, "analysis", "s06_denoised_16S_eDNA", "representative_sequences")), 
                           "data", "dna-sequences.fasta")) %>%
  dplyr::rename(asv_id = seq.name) %>%
  arrange(asv_id) %>%
  rename(asv_sequence = `seq.text`)

# classifications
asv_classification = read_csv(here(run_dir, "output", paste0(config$run$name, "_06_asv_classification.csv")))

# sample map
sample_map = read_csv(here(run_dir, "output", paste0(config$run$name, "_07_sample_id_map.csv")))

```

# join and export ASVs
```{r}
asv_out = asv_controlled %>%
  filter(is.na(control_type),
         asv_count_controlled > 0) %>%
  left_join(asv_seq, by = "asv_id") %>%
  left_join(asv_classification, by = "asv_id") %>%
  filter(!is.na(taxonomic_rank)) %>%
  full_join(sample_map %>%
              select(edna_id,
                     edna_sample_name) %>%
              distinct(), by = c("edna_id", "edna_sample_name")) %>%
  rename(illumina_sample_name = illumina_sample_raw,
         asv_reads_raw = asv_count_raw,
         asv_reads_controlled = asv_count_controlled) %>%
  select(illumina_sample_name,
         edna_id,
         edna_sample_name,
         asv_id,
         asv_sequence,
         asv_reads_raw,
         asv_reads_controlled,
         taxonomic_rank,
         domain,
         kingdom,
         phylum,
         class,
         order,
         family,
         genus,
         species,
         n_hits,
         p_identical_max) %>%
  arrange(illumina_sample_name,
          desc(asv_reads_controlled))


write_csv(asv_out, results_out)
```

# pull metadata
```{r}
# db table pointers
db_edna = tbl(dbcon, Id("survey_data", "edna_collection"))
db_env = tbl(dbcon, Id("survey_data", "environmental"))
db_survey = tbl(dbcon, Id("survey_data", "survey"))
db_visit = tbl(dbcon, Id("survey_data", "visit"))
db_site = tbl(dbcon, Id("survey_data", "site"))
db_region = tbl(dbcon, Id("survey_data", "region"))
db_country = tbl(dbcon, Id("survey_data", "country"))

# survey data
edna_collection = db_edna %>%
  left_join(db_survey, by = "survey_id") %>%
  left_join(db_visit, by = "visit_id") %>%
  left_join(db_site, by = "site_id") %>%
  left_join(db_region, by = "region_id") %>%
  left_join(db_country, by = "country_id") %>%
  filter(edna_id %in% asv_out$edna_id) %>%
  select(edna_id,
         edna_sample_name,
         collection_time,
         edna_latitude,
         edna_longitude,
         comments_edna,
         filter_method,
         filter_size_um,
         filter_start_time,
         filter_end_time,
         filter_volume_ml,
         visit_id,
         date,
         transect,
         site,
         region,
         country) %>%
  collect()

# enviornmental data
env_data = db_env %>%
  left_join(db_survey, by = "survey_id") %>%
  left_join(db_visit, by = "visit_id") %>%
  filter(visit_id %in% edna_collection$visit_id) %>%
  select(visit_id,
         air_temp_c,
         wind_speed_m_s,
         cloud_cover_percent,
         water_temp_c,
         p_h,
         tds_ppm,
         conductivity_us_cm) %>%
  collect() %>%
  group_by(visit_id) %>%
  slice_sample(n = 1) %>%
  ungroup()

edna_env_out = edna_collection %>%
  left_join(env_data, by = "visit_id") %>%
  full_join(asv_out %>%
              select(edna_id) %>%
              distinct(), by = "edna_id") %>%
  select(everything(),
         transect,
         site,
         date,
         visit_id,
         region,
         country)

write_csv(edna_env_out, output_file)
```