---
title: "20_export_prelim_results"
output: html_document
---

# config
```{r}
librarian::shelf(tidyverse, yaml, here, phylotools)

# import run config file
run_dir = here("16S_sequence_processing", "runs", "penn_2026-03-10")

# read in config file
config = read_yaml(here(run_dir, "output", "metadata", "config.yml"))

# control output file
results_out = here(run_dir, "output", paste0(config$run$name, "_20_prelim_results.csv"))

```

# load data
```{r}
# controlled features
asv_controlled = read_csv(here(run_dir, "output", paste0(config$run$name, "_08_asv_controlled.csv")))

# sequences
asv_seq =
  read.fasta(here(run_dir, "analysis", "s06_denoised_16S_eDNA", "representative_sequences", 
                           list.files(here(run_dir, "analysis", "s06_denoised_16S_eDNA", "representative_sequences")), 
                           "data", "dna-sequences.fasta")) %>%
  dplyr::rename(asv_id = seq.name) %>%
  arrange(asv_id) %>%
  rename(asv_sequence = `seq.text`)

# classifications
asv_classification = read_csv(here(run_dir, "output", paste0(config$run$name, "_06_asv_classification.csv")))

# sample map
sample_map = read_csv(here(run_dir, "output", paste0(config$run$name, "_07_sample_id_map.csv")))

```

# join and export
```{r}
asv_out = asv_controlled %>%
  filter(is.na(control_type),
         asv_count_controlled > 0) %>%
  left_join(asv_seq, by = "asv_id") %>%
  left_join(asv_classification, by = "asv_id") %>%
  filter(!is.na(taxonomic_rank)) %>%
  full_join(sample_map %>%
              select(edna_id,
                     edna_sample_name) %>%
              distinct(), by = c("edna_id", "edna_sample_name")) %>%
  rename(asv_reads_controlled = asv_count_controlled) %>%
  select(edna_id,
         edna_sample_name,
         asv_id,
         asv_sequence,
         asv_reads_controlled,
         taxonomic_rank,
         domain,
         kingdom,
         phylum,
         class,
         order,
         family,
         genus,
         species,
         n_hits,
         p_identical_max) %>%
  arrange(edna_sample_name,
          desc(asv_reads_controlled))

write_csv(asv_out, results_out)
```