---
title: "21_join_db_prelim_results"
output: html_document
---

# config
```{r}
librarian::shelf(tidyverse, yaml, dbplyr, RPostgres, DBI, ribbitrrr, here)

# import run config file
prelim_results = read_csv(here("16S_sequence_processing", "runs", "penn_2026-03-10", "output", "penn_2026-03-10_20_prelim_results.csv"))

# establish database connection
dbcon = hopToDB("ribbitr")

# output file
output_file = here("16S_sequence_processing", "runs", "penn_2026-03-10", "output", "penn_2026-03-10_20_prelim_results_metadata.csv")

```

# pull db data
```{r}
# db table pointers
db_edna = tbl(dbcon, Id("survey_data", "edna_collection"))
db_env = tbl(dbcon, Id("survey_data", "environmental"))
db_survey = tbl(dbcon, Id("survey_data", "survey"))
db_visit = tbl(dbcon, Id("survey_data", "visit"))
db_site = tbl(dbcon, Id("survey_data", "site"))
db_region = tbl(dbcon, Id("survey_data", "region"))
db_country = tbl(dbcon, Id("survey_data", "country"))

# survey data
edna_collection = db_edna %>%
  left_join(db_survey, by = "survey_id") %>%
  left_join(db_visit, by = "visit_id") %>%
  left_join(db_site, by = "site_id") %>%
  left_join(db_region, by = "region_id") %>%
  left_join(db_country, by = "country_id") %>%
  filter(edna_id %in% prelim_results$edna_id) %>%
  select(edna_id,
         edna_sample_name,
         collection_time,
         edna_latitude,
         edna_longitude,
         comments_edna,
         filter_method,
         filter_size_um,
         filter_start_time,
         filter_end_time,
         filter_volume_ml,
         visit_id,
         date,
         transect,
         site,
         region,
         country) %>%
  collect()

# enviornmental data
env_data = db_env %>%
  left_join(db_survey, by = "survey_id") %>%
  left_join(db_visit, by = "visit_id") %>%
  filter(visit_id %in% edna_collection$visit_id) %>%
  select(visit_id,
         air_temp_c,
         wind_speed_m_s,
         cloud_cover_percent,
         water_temp_c,
         p_h,
         tds_ppm,
         conductivity_us_cm) %>%
  collect() %>%
  group_by(visit_id) %>%
  slice_sample(n = 1) %>%
  ungroup()

edna_env_out = edna_collection %>%
  left_join(env_data, by = "visit_id") %>%
  full_join(prelim_results %>%
              select(edna_id) %>%
              distinct(), by = "edna_id") %>%
  select(everything(),
         transect,
         site,
         date,
         visit_id,
         region,
         country)

write_csv(edna_env_out, output_file)
```