---
title: "Methods modeling & analysis"
author: "Cob Staines"
output: html_document
---

# load data
```{r}
librarian::shelf(tidyverse, here, yaml, brms, cmdstanr, tidybayes, emmeans)

run_dir_methods = here("16S_sequence_processing", "runs", "methods_2026-03-13")

model_dir = here("analysis", "methods", "output", "models")

# read in config files
config_12s = read_yaml(here(run_dir_methods, "12S", "output", "metadata", "config.yml"))
config_16s = read_yaml(here(run_dir_methods, "16S", "output", "metadata", "config.yml"))

data_combined = read.csv(here(run_dir_methods, "12S", "output", paste0(config_12s$run$name, "_08_asv_controlled_joined.csv")))
```

# aggregate ASV counts
```{r}
# summary stats for samples (ignoring controls)
sample_taxa_count = data_combined %>%
  # drop all controls
  filter(is.na(control_type)) %>%
  group_by(sample_id,
           gene,
           filter_size_um_rz,
           passive_active_rz,
           crispr,
           block,
           extraction_type,
           control_type) %>%
  summarize(
    # number of ASVs (before controls)
    n_asv = sum(detected),
    # number of ASVs (after controls)
    n_asv_controlled = sum(detected_controlled, na.rm = TRUE),
    # number of ASVs classified
    n_asv_controlled_class = sum(detected_controlled & !is.na(taxonomic_rank), na.rm = TRUE),
    # number of ASVs classified chordata
    n_asv_controlled_class_chord = sum(detected_controlled & (phylum == "Chordata"), na.rm = TRUE),
    # number of ASVs classified as amphibians
    n_asv_controlled_class_xamph = sum(detected_controlled & (class == "Amphibia"), na.rm = TRUE),
    # number of ASVs classified as amphibians to the species level
    n_asv_controlled_class_xamph_spp = sum(detected_controlled & (class == "Amphibia") & (taxonomic_rank == "species"), na.rm = TRUE),
    .groups = "drop")

# pivot longer for plotting
sample_taxa_count_long = sample_taxa_count %>%
  pivot_longer(cols = c(n_asv,
                        n_asv_controlled,
                        n_asv_controlled_class,
                        n_asv_controlled_class_chord,
                        n_asv_controlled_class_xamph,
                        n_asv_controlled_class_xamph_spp),
               names_to = "count_type",
               values_to = "n")

# gene
ggplot(sample_taxa_count_long, aes(x = gene, y = n, color = count_type)) +
  geom_boxplot()

# 16s pore size active passive
ggplot(sample_taxa_count %>%
         filter(gene == "16S"), aes(x = passive_active_rz, y = n_asv_controlled_class_xamph_spp, color = filter_size_um_rz)) +
  geom_boxplot()

```

# aggregate ASV reads
```{r}
# summary stats for samples (including controls)
sample_read_count = data_combined %>%
  # drop all controls
  filter(is.na(control_type)) %>%
  group_by(sample_id,
           gene,
           filter_size_um_rz,
           passive_active_rz,
           crispr,
           block,
           extraction_type,
           control_type) %>%
  summarize(
    # number of reads
    n_reads = sum(asv_count),
    # number of reads classified
    n_reads_class = sum(if_else(!is.na(taxonomic_rank), asv_count, 0L), na.rm = TRUE),
    # number of reads classified chordata
    n_reads_class_chord = sum(if_else(phylum == "Chordata", asv_count, 0L), na.rm = TRUE),
    # number of reads classified as amphibians
    n_reads_class_chord_amph = sum(if_else(class == "Amphibia", asv_count, 0L), na.rm = TRUE),
    # number of reads classified as amphibians to the species level
    n_reads_class_chord_amph_spp = sum(if_else((class == "Amphibia") & (taxonomic_rank == "species"), asv_count, 0L), na.rm = TRUE),
    # number of reads classified as human
    n_reads_class_chord_sapien = sum(if_else((species == "sapiens"), asv_count, 0L), na.rm = TRUE),
    .groups = "drop")

# pivot longer for plotting
sample_read_count_long = sample_read_count %>%
  pivot_longer(cols = c(n_reads,
                        n_reads_class,
                        n_reads_class_chord,
                        n_reads_class_chord_amph,
                        n_reads_class_chord_amph_spp,
                        n_reads_class_chord_sapien),
               names_to = "count_type",
               values_to = "n") %>%
  mutate(log10_n = log10(n + 1))

# gene
ggplot(sample_read_count_long, aes(x = gene, y = log10_n, color = count_type)) +
  geom_boxplot()

# 16s pore size active passive
ggplot(sample_taxa_count %>%
         filter(gene == "16S"), aes(x = passive_active_rz, y = n_asv_controlled_class_xamph_spp, color = filter_size_um_rz)) +
  geom_boxplot()

```

# model fitting
```{r}
set_cmdstan_path(Sys.getenv("cmd_stan_path"))

# model 1
m1_znb_read_amph <- brm(
  formula = bf(n_reads_class_chord_sapien ~ gene:crispr + gene:block +filter_size_um_rz + passive_active_rz + extraction_type,
               hu ~ gene:crispr + gene:block + filter_size_um_rz + passive_active_rz + extraction_type,
               shape ~ 1),
  data = sample_read_count,
  family = hurdle_negbinomial(),
  control = list(adapt_delta = 0.95, max_treedepth = 12),
  chains = 4,
  iter = 2000,
  warmup = 1000,
  seed = 124,
  cores = 4,
  backend = "cmdstanr"
)

m1_znb_read_amph <- add_criterion(m1_znb_read_amph, "loo")

saveRDS(m1_znb_read_amph, file = here(model_dir, "m1_znb_read_amph.rds"))
m1_znb_read_amph = readRDS(file = here(model_dir, "m1_znb_read_amph.rds"))

m1_znb_read_sapiens <- brm(
  formula = bf(n_reads_class_chord_sapien ~ gene:crispr + gene:block + filter_size_um_rz + passive_active_rz + extraction_type,
               hu ~ gene:crispr + gene:block + filter_size_um_rz + passive_active_rz + extraction_type,
               shape ~ 1),
  data = sample_read_count,
  family = hurdle_negbinomial(),
  control = list(adapt_delta = 0.95, max_treedepth = 12),
  chains = 4,
  iter = 2000,
  warmup = 1000,
  seed = 124,
  cores = 4,
  backend = "cmdstanr"
)

m1_znb_read_sapiens <- add_criterion(m1_znb_read_sapiens, "loo")

saveRDS(m1_znb_read_sapiens, file = here(model_dir, "m1_znb_read_sapiens.rds"))
m1_znb_read_sapiens = readRDS(file = here(model_dir, "m1_znb_read_sapiens.rds"))

# model 2
m2_znb_read_amph <- brm(
  formula = bf(n_reads_class_chord_sapien ~ gene:crispr + gene:block,
               hu ~ gene:crispr + gene:block,
               shape ~ gene:crispr + gene:block),
  data = sample_read_count,
  family = hurdle_negbinomial(),
  control = list(adapt_delta = 0.95, max_treedepth = 12),
  chains = 4,
  iter = 2000,
  warmup = 1000,
  seed = 124,
  cores = 4,
  backend = "cmdstanr"
)

m2_znb_read_amph <- add_criterion(m2_znb_read_amph, "loo")

saveRDS(m2_znb_read_amph, file = here(model_dir, "m2_znb_read_amph.rds"))
m2_znb_read_amph = readRDS(file = here(model_dir, "m2_znb_read_amph.rds"))

m2_znb_read_sapiens <- brm(
  formula = bf(n_reads_class_chord_sapien ~ gene:crispr + gene:block,
               hu ~ gene:crispr + gene:block,
               shape ~ gene:crispr + gene:block),
  data = sample_read_count,
  family = hurdle_negbinomial(),
  control = list(adapt_delta = 0.95, max_treedepth = 12),
  chains = 4,
  iter = 2000,
  warmup = 1000,
  seed = 124,
  cores = 4,
  backend = "cmdstanr"
)

m2_znb_read_sapiens <- add_criterion(m2_znb_read_sapiens, "loo")

saveRDS(m2_znb_read_sapiens, file = here(model_dir, "m2_znb_read_sapiens.rds"))
m2_znb_read_sapiens = readRDS(file = here(model_dir, "m2_znb_read_sapiens.rds"))

```

# model checks
```{r}
# model_select = m1_znb_asv_cntr
# model_select = m1_znb_asv_cont_chord
# model_select = m1_znb_asv_cont_amph
# model_select = m1_znb_read_amph
model_select = m1_znb_read_sapiens

pp_check(model_select,
         type = "dens_overlay",
         prefix = "ppc",
         ndraws = 100) +
  scale_x_log10()
```

# model interpretation
```{r}
summary(model_select)
```
# human reads
## extract & organize draws
```{r}
model_select = m1_znb_read_sapiens

# hu
# crispr
hu_specs_crispr_sap = emmeans(model_select, 
                   ~ crispr | gene, 
                   dpar = "hu",
                   re_formula = NA)

hu_contrasts_specs_crispr_sap = contrast(hu_specs_crispr_sap, method = "revpairwise")

hu_group_draws_crispr_sap = hu_specs_crispr_sap %>%
  gather_emmeans_draws() %>%
  dplyr::rename(hu = .value) %>%
  mutate(p_detect = 1 - plogis(hu))

hu_contrast_draws_crispr_sap = hu_contrasts_specs_crispr_sap %>%
  gather_emmeans_draws() %>%
  dplyr::rename(hu_crispr = .value)

## block
hu_specs_block_sap = emmeans(model_select, 
                   ~ block | gene, 
                   dpar = "hu",
                   re_formula = NA)

hu_contrasts_specs_block_sap = contrast(hu_specs_block_sap, method = "revpairwise")

hu_group_draws_block_sap = hu_specs_block_sap %>%
  gather_emmeans_draws() %>%
  dplyr::rename(hu = .value) %>%
  mutate(p_detect = 1 - plogis(hu))

hu_contrast_draws_block_sap = hu_contrasts_specs_block_sap %>%
  gather_emmeans_draws() %>%
  dplyr::rename(hu_block = .value)


# mu
# crispr
mu_specs_crispr_sap = emmeans(model_select, 
                   ~ crispr | gene, 
                   dpar = "mu",
                   re_formula = NA)

mu_contrasts_specs_crispr_sap = contrast(mu_specs_crispr_sap, method = "revpairwise")

mu_group_draws_crispr_sap = mu_specs_crispr_sap %>%
  gather_emmeans_draws() %>%
  dplyr::rename(mu = .value)

mu_contrast_draws_crispr_sap = mu_contrasts_specs_crispr_sap %>%
  gather_emmeans_draws() %>%
  dplyr::rename(mu_crispr = .value)

## block
mu_specs_block_sap = emmeans(model_select, 
                   ~ block | gene, 
                   dpar = "mu",
                   re_formula = NA)

mu_contrasts_specs_block_sap = contrast(mu_specs_block_sap, method = "revpairwise")

mu_group_draws_block_sap = mu_specs_block_sap %>%
  gather_emmeans_draws() %>%
  dplyr::rename(mu = .value)

mu_contrast_draws_block_sap = mu_contrasts_specs_block_sap %>%
  gather_emmeans_draws() %>%
  dplyr::rename(mu_block = .value)
```

# amphibian reads
## extract & organize draws
```{r}
model_select = m1_znb_read_amph

# hu
# crispr
hu_specs_crispr_amph = emmeans(model_select, 
                   ~ crispr | gene:block, 
                   dpar = "hu",
                   re_formula = NA)

hu_contrasts_specs_crispr_amph = contrast(hu_specs_crispr_amph, method = "revpairwise")

hu_group_draws_crispr_amph = hu_specs_crispr_amph %>%
  gather_emmeans_draws() %>%
  dplyr::rename(hu = .value) %>%
  mutate(p_detect = 1 - plogis(hu))

hu_contrast_draws_crispr_amph = hu_contrasts_specs_crispr_amph %>%
  gather_emmeans_draws() %>%
  dplyr::rename(hu_crispr = .value)

## block
hu_specs_block_amph = emmeans(model_select, 
                   ~ block | gene:crispr, 
                   dpar = "hu",
                   re_formula = NA)

hu_contrasts_specs_block_amph = contrast(hu_specs_block_amph, method = "revpairwise")

hu_contrast_draws_block_amph = hu_contrasts_specs_block_amph %>%
  gather_emmeans_draws() %>%
  dplyr::rename(hu_block = .value)


# mu
# crispr
mu_specs_crispr_amph = emmeans(model_select, 
                   ~ crispr | gene:block, 
                   dpar = "mu",
                   re_formula = NA)

mu_contrasts_specs_crispr_amph = contrast(mu_specs_crispr_amph, method = "revpairwise")

mu_group_draws_crispr_amph = mu_specs_crispr_amph %>%
  gather_emmeans_draws() %>%
  dplyr::rename(mu = .value)

mu_contrast_draws_crispr_amph = mu_contrasts_specs_crispr_amph %>%
  gather_emmeans_draws() %>%
  dplyr::rename(mu_crispr = .value)

## block
mu_specs_block_amph = emmeans(model_select, 
                   ~ block | gene:crispr, 
                   dpar = "mu",
                   re_formula = NA)

mu_contrasts_specs_block_amph = contrast(mu_specs_block_amph, method = "revpairwise")

mu_contrast_draws_block_amph = mu_contrasts_specs_block_amph %>%
  gather_emmeans_draws() %>%
  dplyr::rename(mu_block = .value)
```

# visualize
```{r}
# hu
ggplot(hu_group_draws_crispr_sap, aes(y = p_detect, x = crispr)) +
  geom_violin(fill = "#66c2a5") +
  theme_minimal() +
  scale_fill_brewer(palette = "Set2") +
  facet_wrap("gene")


ggplot(hu_contrast_draws_crispr_sap, aes(x = -hu_crispr)) +
  stat_halfeye(fill = "#66c2a5",
               .width = c(0.5, 0.95),
               point_interval = mode_hdi) +
  facet_wrap("gene") +
  geom_vline(xintercept = 0, alpha = 1) +
  theme_minimal() +
  labs(
       title = "CRISPR effect on human detection (TRUE - FALSE)",
       x = "Probability density",
       y = "Probability of detection (logit scale) [-]"
       ) +
  theme(text=element_text(size=14))

# number of reads
ggplot(mu_group_draws_crispr_sap, aes(y = mu, x = crispr)) +
  geom_violin(fill = "#8da0cb") +
  theme_minimal() +
  scale_fill_brewer(palette = "Set2") +
  facet_wrap("gene")


ggplot(mu_contrast_draws_crispr_sap, aes(x = mu_crispr)) +
  stat_halfeye(fill = "#8da0cb",
               .width = c(0.5, 0.95),
               point_interval = mode_hdi) +
  facet_wrap("gene") +
  geom_vline(xintercept = 0, alpha = 1) +
  theme_minimal() +
  labs(
       title = "CRISPR effect on human reads (TRUE - FALSE)",
       x = "Probability density",
       y = "Number of reads (log scale) [-]"
       ) +
  theme(text=element_text(size=14))

# hu
ggplot(hu_group_draws_block_sap, aes(y = p_detect, x = block)) +
  geom_violin(fill = "#66c2a5") +
  theme_minimal() +
  scale_fill_brewer(palette = "Set2") +
  facet_wrap("gene")


ggplot(hu_contrast_draws_block_sap, aes(x = -hu_block)) +
  stat_halfeye(fill = "#66c2a5",
               .width = c(0.5, 0.95),
               point_interval = mode_hdi) +
  facet_wrap("gene") +
  geom_vline(xintercept = 0, alpha = 1) +
  theme_minimal() +
  labs(
       title = "block effect on human detection (TRUE - FALSE)",
       x = "Probability density",
       y = "Probability of detection (logit scale) [-]"
       ) +
  theme(text=element_text(size=14))

# number of reads
ggplot(mu_group_draws_block_sap, aes(y = mu, x = block)) +
  geom_violin(fill = "#8da0cb") +
  theme_minimal() +
  scale_fill_brewer(palette = "Set2") +
  facet_wrap("gene")


ggplot(mu_contrast_draws_block_sap, aes(x = mu_block)) +
  stat_halfeye(fill = "#8da0cb",
               .width = c(0.5, 0.95),
               point_interval = mode_hdi) +
  facet_wrap("gene") +
  geom_vline(xintercept = 0, alpha = 1) +
  theme_minimal() +
  labs(
       title = "block effect on human reads (TRUE - FALSE)",
       x = "Probability density",
       y = "Number of reads (log scale) [-]"
       ) +
  theme(text=element_text(size=14))


```

# visualize amphibians
```{r}
# hu
ggplot(hu_group_draws_crispr_amph, aes(y = p_detect, x = crispr)) +
  geom_violin(fill = "#66c2a5") +
  theme_minimal() +
  scale_fill_brewer(palette = "Set2") +
  facet_wrap("gene")


ggplot(hu_contrast_draws_crispr_amph, aes(x = -hu_crispr)) +
  stat_halfeye(fill = "#66c2a5",
               .width = c(0.5, 0.95),
               point_interval = mode_hdi) +
  facet_wrap("gene") +
  geom_vline(xintercept = 0, alpha = 1) +
  theme_minimal() +
  labs(
       title = "CRISPR effect on human detection (TRUE - FALSE)",
       x = "Probability density",
       y = "Probability of detection (logit scale) [-]"
       ) +
  theme(text=element_text(size=14))

# number of reads
ggplot(mu_group_draws_crispr_amph, aes(y = mu, x = crispr)) +
  geom_violin(fill = "#8da0cb") +
  theme_minimal() +
  scale_fill_brewer(palette = "Set2") +
  facet_wrap("gene")


ggplot(mu_contrast_draws_crispr_amph, aes(x = mu_crispr)) +
  stat_halfeye(fill = "#8da0cb",
               .width = c(0.5, 0.95),
               point_interval = mode_hdi) +
  facet_wrap("gene") +
  geom_vline(xintercept = 0, alpha = 1) +
  theme_minimal() +
  labs(
       title = "CRISPR effect on human reads (TRUE - FALSE)",
       x = "Probability density",
       y = "Number of reads (log scale) [-]"
       ) +
  theme(text=element_text(size=14))

# hu
ggplot(hu_group_draws_crispr_amph, aes(y = p_detect, x = block)) +
  geom_violin(fill = "#66c2a5") +
  theme_minimal() +
  scale_fill_brewer(palette = "Set2") +
  facet_wrap("gene")


ggplot(hu_contrast_draws_block_amph, aes(x = -hu_block)) +
  stat_halfeye(fill = "#66c2a5",
               .width = c(0.5, 0.95),
               point_interval = mode_hdi) +
  facet_wrap("gene") +
  geom_vline(xintercept = 0, alpha = 1) +
  theme_minimal() +
  labs(
       title = "block effect on human detection (TRUE - FALSE)",
       x = "Probability density",
       y = "Probability of detection (logit scale) [-]"
       ) +
  theme(text=element_text(size=14))

# number of reads
ggplot(mu_group_draws_crispr_amph, aes(y = mu, x = block)) +
  geom_violin(fill = "#8da0cb") +
  theme_minimal() +
  scale_fill_brewer(palette = "Set2") +
  facet_wrap("gene")


ggplot(mu_contrast_draws_block_amph, aes(x = mu_block)) +
  stat_halfeye(fill = "#8da0cb",
               .width = c(0.5, 0.95),
               point_interval = mode_hdi) +
  facet_wrap("gene") +
  geom_vline(xintercept = 0, alpha = 1) +
  theme_minimal() +
  labs(
       title = "block effect on human reads (TRUE - FALSE)",
       x = "Probability density",
       y = "Number of reads (log scale) [-]"
       ) +
  theme(text=element_text(size=14))


```

```{r}
# newdata_gene = expand_grid(gene = c("12S", "16S")) %>%
#   mutate(passive_active_rz = "Active",
#          filter_size_um_rz = 5.0,
#          crispr = FALSE,
#          block = FALSE,
#          extraction_type = "Tissue")
# 
# epred_gene = epred_draws(model_select,
#                          newdata = newdata_gene,
#                          re_formula = NA)

# distrivbution
mu_specs = emmeans(model_select, 
                   ~ gene | crispr:block, 
                   dpar = "mu",
                   re_formula = NA)

mu_contrasts_specs = contrast(mu_specs, method = "revpairwise")

mu_group_draws = mu_specs %>%
  gather_emmeans_draws() %>%
  dplyr::rename(mu = .value)

mu_contrast_draws = mu_contrasts_specs %>%
  gather_emmeans_draws() %>%
  dplyr::rename(mu_gene = .value)

mu_contrast_agg = mu_contrast_draws %>%
  group_by(contrast) %>%
  summarize(hdi_50 = hdi(mu_gene, ci = 0.50),
            hdi_89 = hdi(mu_gene, ci = 0.89),
            hdi_95 = hdi(mu_gene, ci = 0.95),
            ratio_positive = sum(mu_gene > 0) / n(),
            mu_median = median(mu_gene),
            .groups = "drop") %>%
  mutate(
    hdi_zero_50 = case_when(
      hdi_50[1] > 0 | hdi_50[2] < 0 ~ TRUE,
      .default = FALSE
    ),
    hdi_zero_89 = case_when(
      hdi_89[1] > 0 | hdi_89[2] < 0 ~ TRUE,
      .default = FALSE
    ),
    hdi_zero_95 = case_when(
      hdi_95[1] > 0 | hdi_95[2]< 0 ~ TRUE,
      .default = FALSE
    ))

# newdata_gene = expand_grid(gene = c("12S", "16S")) %>%
#   mutate(passive_active_rz = "Active",
#          filter_size_um_rz = 5.0,
#          crispr = FALSE,
#          block = FALSE,
#          extraction_type = "Tissue")
# 
# epred_gene = epred_draws(model_select,
#                          newdata = newdata_gene,
#                          re_formula = NA)

```

# hypothesis testing
```{r}

# ggplot(epred_gene, aes(y = .epred, x = gene)) +
#   geom_boxplot() +
#   theme_minimal()

# hu
ggplot(hu_group_draws, aes(y = p_detect, x = gene)) +
  geom_violin() +
  theme_minimal() +
  scale_fill_brewer(palette = "Set2") +
  facet_grid(crispr ~ block) +
  labs(x = "crispr", y = "block")


ggplot(hu_contrast_draws, aes(x = -hu_gene)) +
  stat_halfeye(fill = "#66c2a5",
               .width = c(0.5, 0.95),
               point_interval = mode_hdi) +
  facet_grid(crispr ~ block) +
  geom_vline(xintercept = 0, alpha = 1) +
  theme_minimal() +
  labs(
       title = "Gene effect on amphibian detection (16S - 12S)",
       x = "Probability density",
       y = "Probability of detection (logit scale) [-]"
       ) +
  theme(text=element_text(size=14))

# number of reads
ggplot(mu_group_draws, aes(y = mu, x = gene)) +
  geom_violin() +
  theme_minimal() +
  scale_fill_brewer(palette = "Set2") +
  facet_grid(crispr ~ block)


ggplot(mu_contrast_draws, aes(x = mu_gene)) +
  stat_halfeye(fill = "#8da0cb",
               .width = c(0.5, 0.95),
               point_interval = mode_hdi) +
  facet_grid(crispr ~ block) +
  geom_vline(xintercept = 0, alpha = 1) +
  theme_minimal() +
  labs(
       title = "Gene effect on amphibian reads (16S - 12S)",
       x = "Probability density",
       y = "Number of reads (log scale) [-]"
       ) +
  theme(text=element_text(size=14))

```