---
title: "Sequence analysis"
output: html_document
---

# Created by: Cob Staines (cobstainesconsulting@gmail.com)

# config
```{r}
## Load in Libraries (install them in you need them.)
librarian::shelf(tidyverse, yaml, phylotools, here)

# read in config files
config_12s = read_yaml(here("16S_sequence_processing", "runs/methods_2026-03-13/12S/output/metadata/config.yml"))
config_16s = read_yaml(here("16S_sequence_processing", "runs/methods_2026-03-13/16S/output/metadata/config.yml"))



```

# load data files
```{r}
# feature tables
## 12s
feature_table_12s =
  read_tsv(here("16S_sequence_processing", paste0(config_12s$run$runDir, "/analysis/s06_denoised_", config_12s$taxonomy$gene, "_eDNA/sample_table/feature-table.tsv")), skip = 1) %>%
  as.data.frame() %>%
  rename("asv_id" = "#OTU ID") %>%
  arrange(asv_id)

feature_long_12s = feature_table_12s %>%
  pivot_longer(cols = -asv_id,
               names_to = "sample_id",
               values_to = "asv_count") %>%
  filter(asv_count != 0) %>%
  arrange(sample_id) %>%
  select(sample_id,
         asv_id,
         asv_count)

asv_totals_12s = feature_long_12s %>%
  group_by(asv_id) %>%
  summarise(asv_total_count = sum(asv_count),
            sample_count = n_distinct(sample_id),
            samples = paste(sort(unique(sample_id)), collapse = ", ")) %>%
  arrange(desc(asv_total_count))

## 16S
feature_table_16s =
  read_tsv(here("16S_sequence_processing", paste0(config_16s$run$runDir, "/analysis/s06_denoised_", config_16s$taxonomy$gene, "_eDNA/sample_table/feature-table.tsv")), skip = 1) %>%
  as.data.frame() %>%
  rename("asv_id" = "#OTU ID") %>%
  arrange(asv_id)

feature_long_16s = feature_table_16s %>%
  pivot_longer(cols = -asv_id,
               names_to = "sample_id",
               values_to = "asv_count") %>%
  filter(asv_count != 0) %>%
  arrange(sample_id) %>%
  select(sample_id,
         asv_id,
         asv_count)

asv_totals_16s = feature_long_16s %>%
  group_by(asv_id) %>%
  summarise(asv_total_count = sum(asv_count),
            sample_count = n_distinct(sample_id),
            samples = paste(sort(unique(sample_id)), collapse = ", ")) %>%
  arrange(desc(asv_total_count))

# ASV sequence tables
## 12s
seq_asv_12s =
  read.fasta(here("16S_sequence_processing", paste0(config_12s$run$runDir, "/analysis/s06_denoised_", config_12s$taxonomy$gene, "_eDNA/representative_sequences/", 
                           list.files(here("16S_sequence_processing", paste0(config_12s$run$runDir, "/analysis/s06_denoised_", config_12s$taxonomy$gene, "_eDNA/representative_sequences"))), 
                           "/data/dna-sequences.fasta"))) %>%
  dplyr::rename(asv_id = seq.name) %>%
  arrange(asv_id) %>%
  mutate(bp = str_length(seq.text),
         gene = "12S")

## 16s
seq_asv_16s =
  read.fasta(here("16S_sequence_processing", paste0(config_16s$run$runDir, "/analysis/s06_denoised_", config_16s$taxonomy$gene, "_eDNA/representative_sequences/", 
                           list.files(here("16S_sequence_processing", paste0(config_16s$run$runDir, "/analysis/s06_denoised_", config_16s$taxonomy$gene, "_eDNA/representative_sequences"))), 
                           "/data/dna-sequences.fasta"))) %>%
  dplyr::rename(asv_id = seq.name) %>%
  arrange(asv_id) %>%
  mutate(bp = str_length(seq.text),
         gene = "16S")

# classifier sequence tables
## 12s
seq_class_12s =
  read.fasta(here("16S_sequence_processing", "vertebrata12s_classifier", "Vertebrata12S_derep1_seqs_extracted",
                               list.files(here("16S_sequence_processing", "vertebrata12s_classifier", "Vertebrata12S_derep1_seqs_extracted")), "data", "dna-sequences.fasta")) %>%
  dplyr::rename(taxon_id = seq.name) %>%
  arrange(taxon_id) %>%
  mutate(bp = str_length(seq.text),
         gene = "12S")

## 16s
seq_class_16s =
  read.fasta(here("16S_sequence_processing", "vertebrata16s_classifier", "Vertebrata16S_derep1_seqs_extracted",
                               list.files(here("16S_sequence_processing", "vertebrata16s_classifier", "Vertebrata16S_derep1_seqs_extracted")), "data", "dna-sequences.fasta")) %>%
  dplyr::rename(taxon_id = seq.name) %>%
  arrange(taxon_id) %>%
  mutate(bp = str_length(seq.text),
         gene = "16S")

# classifier taxonomy
## 12s
taxa_class_12s = read_tsv(here("16S_sequence_processing", "vertebrata12s_classifier", "Vertebrata12S_derep1_taxa_extracted",
                               list.files(here("16S_sequence_processing", "vertebrata12s_classifier", "Vertebrata12S_derep1_taxa_extracted")), "data", "taxonomy.tsv")) %>%
  rename(taxon_id = `Feature ID`,
         taxon = Taxon) %>%
  separate(taxon, into = c("k", "p", "c", "o", "f", "g", "s"), sep = ";") %>%
  mutate(across(everything(), ~ str_remove(., "^[a-z]__"))) %>%
  rename(kingdom = k,
         phylum = p,
         class = c,
         order = o,
         family = f,
         genus = g,
         species = s) %>%
  mutate(domain = "Eukaryota") %>%
  arrange(taxon_id) %>%
  select(taxon_id,
         domain,
         everything())

## 16s
taxa_class_16s = read_tsv(here("16S_sequence_processing", "vertebrata16s_classifier", "Vertebrata16S_derep1_taxa_extracted",
                               list.files(here("16S_sequence_processing", "vertebrata16s_classifier", "Vertebrata16S_derep1_taxa_extracted")), "data", "taxonomy.tsv")) %>%
  rename(taxon_id = `Feature ID`,
         taxon = Taxon) %>%
  separate(taxon, into = c("k", "p", "c", "o", "f", "g", "s"), sep = ";") %>%
  mutate(across(everything(), ~ str_remove(., "^[a-z]__"))) %>%
  rename(kingdom = k,
         phylum = p,
         class = c,
         order = o,
         family = f,
         genus = g,
         species = s) %>%
  mutate(domain = "Eukaryota") %>%
  arrange(taxon_id) %>%
  select(taxon_id,
         domain,
         everything())


```

# sequence lengths
```{r}
seq_asv = bind_rows(seq_asv_12s,
                    seq_asv_16s)

ggplot(seq_asv, aes(x = bp, fill = gene)) +
  geom_histogram() +
  facet_wrap("gene", scales = "free_x") +
  theme_minimal()
```

# classifier taxonomy sequences
```{r}
seq_class = bind_rows(seq_class_12s,
                      seq_class_16s)

ggplot(seq_class, aes(x = bp, fill = gene)) +
  geom_histogram() +
  facet_wrap("gene", scales = "free_x") +
  theme_minimal()

```

# classifier taxonomy read counts
```{r}
taxa_class_12s_count = taxa_class_12s %>%
  group_by(kingdom,
           phylum,
           class,
           order,
           family,
           genus,
           species) %>%
  count() %>%
  mutate(gene = "12S")


taxa_class_16s_count = taxa_class_16s %>%
  group_by(kingdom,
           phylum,
           class,
           order,
           family,
           genus,
           species) %>%
  count() %>%
  mutate(gene = "16S")

taxa_class_count = bind_rows(taxa_class_12s_count,
                             taxa_class_16s_count)

cumcount <- function(df, bins, column = "n") {
  tibble(sequences_n = bins) %>%
    rowwise() %>%
    mutate(
      taxa_n   = sum(df[[column]] == sequences_n, na.rm = TRUE),
      taxa_cum_n = sum(df[[column]] >= sequences_n, na.rm = TRUE)
    ) %>%
    ungroup()
}

cumcount_bins = seq(1, 50)

cumcount_12s_class = cumcount(taxa_class_12s_count, cumcount_bins) %>%
  mutate(gene = "12S",
         taxa = "all")
cumcount_16s_class = cumcount(taxa_class_16s_count, cumcount_bins) %>%
  mutate(gene = "16S",
         taxa = "all")

cumcount_12s_class_amph = cumcount(taxa_class_12s_count %>%
                                    filter(class == "Amphibia"), cumcount_bins) %>%
  mutate(gene = "12S",
         taxa = "Amphibia")
cumcount_16s_class_amph = cumcount(taxa_class_16s_count %>%
                                    filter(class == "Amphibia"), cumcount_bins) %>%
  mutate(gene = "16S",
         taxa = "Amphibia")

cumcount_class = bind_rows(cumcount_12s_class,
                           cumcount_16s_class,
                           cumcount_12s_class_amph,
                           cumcount_16s_class_amph
                           )

ggplot(cumcount_class, aes(x = sequences_n, y = taxa_n,  linetype = taxa, color = gene)) +
  geom_line() +
  theme_minimal() +
  scale_y_log10()


ggplot(cumcount_class, aes(x = sequences_n, y = taxa_cum_n,  linetype = taxa, color = gene)) +
  geom_line() +
  theme_minimal() +
  scale_y_log10()

```