---
title: "copy_seqs_by_system"
author: "Cob Staines"
output: html_document
---

# Copy Sequence Files by System

This is a utility script which parses through nested folders for .fastq sequencing files, identifies which study system they belong to, and supports copying only files for a desired system to a desired repository

# Config
```{r}
librarian::shelf(tidyverse, here, janitor)

# directory to search recursively
search_dir = here(Sys.getenv("data_dir"), "edna_results")

# system(s) of interest: any of: brazil, panama, pennsylvania, california
soi = "pennsylvania"

# directory to copy files to
copy_dir = here("16S_sequence_processing", "runs", "penn_2026-03-10", "sequences")

```

# Parse search directory
```{r}
search_dir_files = tibble(relative_filepath = c(list.files(search_dir, recursive = TRUE))) %>%
  filter(str_detect(relative_filepath, "\\.fastq(\\.gz)?$")) %>%
  mutate(absolute_filepath = here(search_dir, relative_filepath),
         filename = basename(relative_filepath),
         filebase = gsub(".fastq", "", gsub(".gz", "", filename)),
         batch_id = str_match(filebase, "^([A-Za-z0-9]+-)")[,2],
         processing_id = str_match(filebase, "(_S[0-9]+_L[0-9]+_R[12]_[0-9]+)$")[,2],
         read_dir = case_when(
           grepl("_R1_", processing_id) ~ "forward",
           grepl("_R2_", processing_id) ~ "reverse",
           .default = NA),
         sample_id = str_remove(str_remove(filebase, processing_id), batch_id),
         system = case_when(
           grepl("PAN", sample_id) ~ "panama",
           grepl("Pe|PENN|PCI|Tissue|CRISPR|block|12S|16S", sample_id) ~ "pennsylvania",
           grepl("BR", sample_id) ~ "brazil",
           grepl("SN|BII", sample_id) ~ "california",
           .default = NA
         ),
         control = case_when(
           grepl("negative", sample_id, ignore.case = TRUE) ~ "negative",
           grepl("positive", sample_id, ignore.case = TRUE) ~ "positive",
           .default = NA
         )) %>%
  filter(sample_id != "0",
         !grepl("Blank", sample_id))

# check for duplicates
dupes_samples_1 = get_dupes(search_dir_files, sample_id, read_dir)
```

# Filter to system of interest
```{r}
# files of interest
foi = search_dir_files %>%
  filter(system %in% soi) %>%
  # drop duplicates
  arrange(relative_filepath) %>%
  group_by(sample_id, read_dir) %>%
  slice_head(n = 1) %>%
  ungroup()


# check for duplicate copies of sample/read_dir
dupes_samples_2 = get_dupes(foi, sample_id, read_dir)

if (nrow(dupes_samples_2) > 0) {
  stop("Unexpected duplicate samples found. Aborting.")
}

# check two reads per sample (forward & reverse)
dupes_samples_3 = foi %>%
  group_by(sample_id) %>%
  count() %>%
  filter(n != 2)

if (nrow(dupes_samples_3) > 0) {
  stop(paste0("Unpaired reads found for the following samples:\n\t", paste0(dupes_samples_3$sample_id, collapse = "\n\t")))
}

```

# Copy files to copy directory
```{r}
# delete all existing files in directory first
if (length(list.files(search_dir)) > 0) {
  drop_input = readline(prompt = "Files exist in the copy directory. Do you want to delete these files before copying? [y/n]"); 
  
  if (tolower(drop_input == "y")) {
    cat("Deleting existing files in copy directory.\n")
    unlink(here(copy_dir, "*"))
  } else if (tolower(drop_input == "n")) {
    cat("Leaving existing files in copy directory. Proceeding to copy new files.\n")
  } else {
    stop("Input not recognized. Copy aborted.")
  }
}

cat(paste0("Copying ", as.character(nrow(foi)), " sequence files to copy directory... "))

file.copy(foi$absolute_filepath, copy_dir)

cat("done.")
```